version: "2.4"
services:
#  hr-platform:
#    image: hr-platform-2022
#    build:
#      context: ./
#      dockerfile: docker/Dockerfile
#    container_name: hr-platform
#    restart: always
#    env_file: .env
#    ports:
#      - 8099:8099
#    networks:
#      - hr-network

#  redis:
#    image: redis:alpine
#    container_name: redis_db
#    command: redis-server --appendonly yes
#    ports:
#      - 6379:6379
#    volumes:
#      - ./data:/data
#    restart: always
#    networks:
#      - hr-network

  postgres:
    container_name: ${APP_NAME}-postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5434:5432"
    restart: unless-stopped
    networks:
      - hr-network

  minio-s3:
    image: minio/minio
    container_name: db-ingestor-minio
    restart: always
    #    command: minio server /data/minio/
    command: minio server /data/minio/ --address :9001
    ports:
      - ${S3_UI_PORT}:9001
    environment:
      MINIO_ACCESS_KEY: ${S3_KEY}
      MINIO_SECRET_KEY: ${S3_SECRET}
    volumes:
      - s3:/data/minio
    networks:
      - hr-network

volumes:
  postgres:

networks:
  hr-network: